name: chat_app1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-78.0.dev

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  firebase_storage: ^12.1.3
  firebase_messaging: ^15.0.4
  cloud_firestore: ^5.2.1
  cloud_functions: ^5.0.4
  intl: ^0.19.0
  hexcolor: ^3.0.1
  google_fonts: ^6.2.1
  text_divider: ^1.0.0
  google_sign_in: ^6.2.1
  email_validator: ^3.0.0
  shared_preferences: ^2.3.1
  flutter_screenutil: ^5.9.3
  firebase_database: ^11.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/backGroundImage.jpeg
    - assets/messageBackGroundImage.jpg


  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Light.ttf
        - asset: fonts/Lato-Black.ttf
        - asset: fonts/Lato-Italic.ttf