// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGglaCd8ASX35H8hlwL1HZeTglVq9N1_w',
    appId: '1:31541367210:web:f30ab96d511c431a941bd3',
    messagingSenderId: '31541367210',
    projectId: 'chatapp-42a40',
    authDomain: 'chatapp-42a40.firebaseapp.com',
    storageBucket: 'chatapp-42a40.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi9Twl1C5mnfhquTpJ2F6fmMF5BcD2qY8',
    appId: '1:31541367210:android:32e51c6d2e3aa34e941bd3',
    messagingSenderId: '31541367210',
    projectId: 'chatapp-42a40',
    storageBucket: 'chatapp-42a40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2TKGtmylQqacjStl3H1_vHF3l2OGc5c0',
    appId: '1:31541367210:ios:ad62e9c5eab8fc84941bd3',
    messagingSenderId: '31541367210',
    projectId: 'chatapp-42a40',
    storageBucket: 'chatapp-42a40.appspot.com',
    iosBundleId: 'com.example.chatApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2TKGtmylQqacjStl3H1_vHF3l2OGc5c0',
    appId: '1:31541367210:ios:ad62e9c5eab8fc84941bd3',
    messagingSenderId: '31541367210',
    projectId: 'chatapp-42a40',
    storageBucket: 'chatapp-42a40.appspot.com',
    iosBundleId: 'com.example.chatApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGglaCd8ASX35H8hlwL1HZeTglVq9N1_w',
    appId: '1:31541367210:web:57bc5afb835fba5e941bd3',
    messagingSenderId: '31541367210',
    projectId: 'chatapp-42a40',
    authDomain: 'chatapp-42a40.firebaseapp.com',
    storageBucket: 'chatapp-42a40.appspot.com',
  );
}
